# Repo B / azure-pipeline.yml

trigger:
- master


resources:
  repositories:
    - repository: 'templates'
      type: 'github'
      name: 'SivaSuryaPrasad/TestRepo'
      endpoint: 'serviceconnection4'

steps:

  - template: 'testing/test.yml@templates'  # Template reference