# Repo B / azure-pipeline.yml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

resources:
  repositories:
    - repository: templates
      type: github
      name: SivaSuryaPrasad/TestRepo
      

stages:
- template: testing/test.yml@templates  # Template reference